name: Build Scriptable Bundle

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build bundle
        run: npx rollup -c

      - name: Upload bundle
        uses: actions/upload-artifact@v4
        with:
          name: scriptable-bundle
          path: dist/Wallet Widget.js
